import schemasRegex from "./regex";

export interface Token {
  name: string;
  values: string[];
}

/**
 * Checks schemas generated by schemasRegex for matches in the given pattern.
 * Returns a match or "not_found" if no match is found.
 * 
 * @param pattern - The input string to be checked
 * @returns An object containing the matched schema name and values
 */
export function getPatternValues(pattern: string): Token {
  for (const [schemaName, regex] of Object.entries(schemasRegex)) {
    const match = pattern.match(regex);
    if (match) {
      return {
        name: schemaName,
        values: match.slice(1) // Remove object types in an array + first element
      };
    }
  }

  return {
    name: "not_found",
    values: [pattern]
  }
}
